### ISSUE TITLE
Ainize Workspace에서 `main.infer` 실행 확인하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/wisdomify#10]
정말 감사하게도 [Common Computer](https://comcom.ai/ko/) 스타트업으로부터 GPU & deploy 서버 영구지원을 받게되었다.
즉 고사양 컴퓨터의 shell에 영구접근 권한을 얻었다!!
여기에 접속해서 프로젝트를 클론하고, 리드미에 쓴대로 한번  quick start를 해보자.

**Comment by eubinecto** [comment]
version_0.zip을 링크로 걸어두지 말고, 그냥 `wget`으로 받는 편이 훨편할 것 같다 - https://superuser.com/a/486351

예를 들면 요렇게:
```bash
wget version_0.zip https://www.dropbox.com/s/tw491n5dnk8195c/version_0.zip?dl=1
```

일단 이건 나중에 수정하겠음.

**Comment by eubinecto** [comment]
프로젝트를 clone하고 `main.infer` 를 실행해보니 다음과 같은 오류가 뜬다:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/wisdomify/wisdomify/main/infer.py", line 53, in <module>
    main()
  File "/workspace/wisdomify/wisdomify/main/infer.py", line 47, in main
    for results in wisdomifier.wisdomify(sents=[desc]):
  File "/workspace/wisdomify/wisdomify/models.py", line 96, in wisdomify
    S_word_logits = self.rd.S_word(S_subword)  # (N, |V|).
  File "/workspace/wisdomify/wisdomify/models.py", line 54, in S_word
    S_word = S_subword.gather(dim=-1, index=word2subs)  # (N, K, |S|) -> (N, K, |V|)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking arugment for argument index in method wrapper_gather)
```

로컬에서 했을 때, 그리고 내 서버에서 gtx2070으로 돌렸을 때도 오류가 없었는데..음.. 여기에서 돌리니 이런 오류가 뜬다.
일단 브랜치를 따서 핫픽스를 해보자.

**Comment by eubinecto** [comment]
ainize에서 VsCode를 제공한다! 여기에서 핫픽스를 해보자. 정말 좋은 기능인듯!

다시 살펴보니, 여기에서 `vocab2subwords`를 device에 올려주는 것을 깜박함.  다음과 같이 수정함: 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/56193069/124070182-60ce5e00-da78-11eb-8080-d5cab20cadc8.png">

## 이참에 git 명령어 복습
create a new branch:
```
git branch feature_10
```

switch to a branch
```
git switch feature_10
```

Note that this won't create the branch on remote. In order to push the commits made on a new local branch, you must push branch to remote first (*[How to fix fatal:the current branch master has no upstream branch](https://www.educative.io/edpresso/how-to-fix-fatalthe-current-branch-master-has-no-upstream-branch)*):
```
git push -u origin feature_10
```
once this is done, you can now start pushing the commits by just typing push on the branch, like so:
```
git push
```
 
If you want to amend the most recent commit:
```
git amend
```
-  this will open a vim editor. As for writing & editing in vim, referring to this article may help -https://www.cyberciti.biz/faq/how-do-i-save-changes-in-vim/

**Comment by eubinecto** [comment]
https://github.com/eubinecto/wisdomify/issues/10#issuecomment-871927679 
`wget`으로 바로 모델 다운로드 받을 수 있도록 리드미 변경.

**Comment by eubinecto** [comment]
실행 성공!:
```
(wisdomifyenv) root@owzeywysbowkytjestgbmfco-69f949b44f-5wj47:~/wisdomify# python3 -m wisdomify.main.infer --ver="version_0" --desc="까불지말고 침착하게 개발하자"
/workspace/wisdomify/wisdomifyenv/lib/python3.7/site-packages/pytorch_lightning/metrics/__init__.py:44: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  "`pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package"
Some weights of the model checkpoint at beomi/kcbert-base were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
### desc: 까불지말고 침착하게 개발하자 ###
0: (원숭이도 나무에서 떨어진다, 0.8152)
1: (꿩 대신 닭, 0.0996)
2: (고래 싸움에 새우 등 터진다, 0.0628)
3: (산넘어 산, 0.0192)
4: (갈수록 태산, 0.0030)
5: (등잔 밑이 어둡다, 0.0002)
6: (가는 날이 장날, 0.0000)
7: (핑계 없는 무덤 없다, 0.0000)
8: (서당개 삼 년이면 풍월을 읊는다, 0.0000)
9: (소문난 잔치에 먹을 것 없다, 0.0000)
```
